<a href="https://colab.research.google.com/github/leejsya/PyTorch/blob/main/Tensor_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import torch

# 1. list를 tensor로 변환

In [3]:
data_list = [1, 2]
tensor = torch.tensor(data_list)

In [4]:
print(f"tensor: {tensor}\n")
print(f"class type: {type(tensor)}\n")
print(f"data type: {tensor.dtype}\n")
print(f"dimension: {tensor.ndim}\n")
print(f"shape: {tensor.shape}") # tensor.size()와 같은 결과

tensor: tensor([1, 2])

class type: <class 'torch.Tensor'>

data type: torch.int64

dimension: 1

shape: torch.Size([2])


# 2. np array를 tensor로 변환

In [5]:
data_np = np.array(
    [[1, 2],
    [3, 4]]
)

#### 방법 1 : `tensor()`
- data_np의 데이터를 복사해서 tensor를 생성. (메모리를 공유하지 않음)

In [6]:
tensor_np = torch.tensor(data_np)
tensor_np

tensor([[1, 2],
        [3, 4]])

#### 방법 2 : `from_numpy()`
- data_np의 데이터를 가져와 tensor를 생성. (메모리를 공유함)

In [7]:
tensor_from_numpy = torch.from_numpy(data_np)
tensor_from_numpy

tensor([[1, 2],
        [3, 4]])

#### 두 방법의 차이점:

In [8]:
# 차이점
data_np[0, 0] = -1
print(f"tensor():\n{tensor_np}\n")
print(f"from_numpy():\n{tensor_from_numpy}")

tensor():
tensor([[1, 2],
        [3, 4]])

from_numpy():
tensor([[-1,  2],
        [ 3,  4]])


-> 두 결과가 다른 것을 볼 수 있다.

# 3. 데이터 타입 지정


In [9]:
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor.dtype

torch.float32

# 4. random값 tensor 생성
#### (1) 0과 1 사이의 랜덤한 값으로 tensor 생성

In [10]:
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand([2, 3])
tensor3 = torch.rand((2, 3))
# 모두 같은 의미

In [11]:
print(f"tensor1: {tensor1}\n")
print(f"tensor2: {tensor2}\n")
print(f"tensor3: {tensor3}\n")

tensor1: tensor([[0.8076, 0.4833, 0.8997],
        [0.8881, 0.7902, 0.1008]])

tensor2: tensor([[0.7260, 0.5750, 0.3696],
        [0.3578, 0.4025, 0.5400]])

tensor3: tensor([[0.9986, 0.8268, 0.5657],
        [0.4600, 0.0115, 0.6316]])



In [12]:
# 만약 0과 10 사이의 랜덤한 값으로 tensor를 생성하려면
min_val = 0
max_val = 10
rand_tensor = min_val + (max_val - min_val) * torch.rand(2, 3)
rand_tensor

tensor([[4.1896, 9.0325, 8.2464],
        [4.8693, 9.6185, 4.1081]])

#### (2) avg가 0, std가 1인 random값 tensor 생성

In [13]:
# avg가 0, std가 1인 random tensor 생성.
tensor = torch.randn(2, 3)
tensor

tensor([[ 0.6694,  0.3382, -0.9199],
        [ 0.0802, -0.4384, -0.8295]])

In [14]:
# 만약 avg가 5, std가 2인 random tensor를 생성하려면
avg = 5
std = 2
tensor = avg + 2 * torch.randn(2, 3)
tensor

tensor([[5.7272, 9.3262, 9.0827],
        [3.0852, 7.7905, 5.5841]])

# 5. 특정한 값을 갖는 tensor 생성

In [15]:
# 값이 전부 0인 tensor
zeros_tensor = torch.zeros(2, 3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [16]:
# 값이 전부 1인 tensor
ones_tensor = torch.ones(2, 3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
# 값이 전부 7인 tensor
s_tensor = torch.full((2, 3), 7)
s_tensor

tensor([[7, 7, 7],
        [7, 7, 7]])

# 6. tensor를 np array로 변환

In [18]:
t_tensor = torch.ones(2, 2)
t_tensor

tensor([[1., 1.],
        [1., 1.]])

#### 방법 1 : `numpy()`
- t_tensor와 메모리를 공유함

In [19]:
np_array = t_tensor.numpy()
np_array

array([[1., 1.],
       [1., 1.]], dtype=float32)

#### 방법 2 : `np.array(tensor)`
- t_tensor와 메모리를 공유하지 않음

In [20]:
np_array2 = np.array(t_tensor)
np_array2

/tmp/ipykernel_904/2988097014.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np_array2 = np.array(t_tensor)


array([[1., 1.],
       [1., 1.]], dtype=float32)

#### 두 방법의 차이점:

In [21]:
t_tensor[0, 0] = -1

In [22]:
print(f"numpy():\n{np_array}\n")
print(f"np.array():\n{np_array2}\n")

numpy():
[[-1.  1.]
 [ 1.  1.]]

np.array():
[[1. 1.]
 [1. 1.]]



# 7. 기본 tensor 연산

In [23]:
a = torch.tensor(
    [[1, 2],
     [3, 4]]
)
b = torch.tensor(
    [[1, 1],
     [2, 2]]
)

In [24]:
print(a + b)
print(torch.add(a, b))

tensor([[2, 3],
        [5, 6]])
tensor([[2, 3],
        [5, 6]])


In [25]:
print(a * b)
print(torch.multiply(a, b))

tensor([[1, 2],
        [6, 8]])
tensor([[1, 2],
        [6, 8]])


In [26]:
# 행렬 곱은 두 행렬의 데이터 타입이 일치해야만 연산 가능.
print(torch.matmul(a, b))
print(a @ b)

tensor([[ 5,  5],
        [11, 11]])
tensor([[ 5,  5],
        [11, 11]])


In [27]:
# 데이터 타입 변경
print(f"old: {a.dtype}")
a_new = a.to(torch.float32)
print(f"new: {a_new.dtype}")

old: torch.int64
new: torch.float32


# 8. BroadCasting
shape가 작은 tensor를 큰 tensor에 맞게 자동으로 확장해 연산을 수행한다.

In [28]:
a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
    ]
)

b = torch.tensor(
    [1, -1, 2],
)

print(f"a의 shape: {a.shape}")
print(f"b의 shape: {b.shape}")

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([3])


#### BroadCasting이 안되는 경우:

In [29]:
a = torch.tensor(
    [
        [1 ,2 ,3],
        [4, 5, 6],
    ]
)
b = torch.tensor(
    [1, -1],
)
print(f"a의 shape: {a.shape}")
print(f"b의 shape: {b.shape}")

a의 shape: torch.Size([2, 3])
b의 shape: torch.Size([2])


In [30]:
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

# 9. Tensor의 shape 변환

#### (1) reshape

In [31]:
x = torch.randn(3, 4)
x

tensor([[ 0.6983,  1.1007,  0.5572, -1.2131],
        [ 0.8970,  0.8252,  3.5157,  0.5296],
        [ 0.1608,  1.2598, -0.0457, -1.2647]])

In [32]:
res0 = x.reshape(2, 6)
res0

tensor([[ 0.6983,  1.1007,  0.5572, -1.2131,  0.8970,  0.8252],
        [ 3.5157,  0.5296,  0.1608,  1.2598, -0.0457, -1.2647]])

In [33]:
# 원소의 개수가 다르기 때문에 오류. 2x5=10
x.reshape(2, 5)

RuntimeError: shape '[2, 5]' is invalid for input of size 12

In [34]:
# -1을 넣었을 때, 그 위치에 원소 개수에 맞춰 알아서 크기를 설정해줌.
res1 = x.reshape(-1, 2, 3)
res1

tensor([[[ 0.6983,  1.1007,  0.5572],
         [-1.2131,  0.8970,  0.8252]],

        [[ 3.5157,  0.5296,  0.1608],
         [ 1.2598, -0.0457, -1.2647]]])

#### (2) permuted

In [35]:
x2 = torch.randn(2, 3, 4)
permuted = x2.permute(2, 0, 1) # 차원의 인덱스를 파라미터로 입력.
permuted # 4 x 2 x 3 tensor가 됨.

tensor([[[-0.0955, -0.5312, -0.5526],
         [-1.4194,  0.0053,  0.4952]],

        [[ 0.5407,  0.1181,  1.4906],
         [ 0.0903, -0.1249,  0.6897]],

        [[ 0.4327,  0.9463,  0.9274],
         [-0.9409,  0.3029,  0.2311]],

        [[-0.3327,  2.7346,  2.0950],
         [ 0.2836, -0.4187, -1.4147]]])

In [36]:
permuted.size()

torch.Size([4, 2, 3])

#### (3) squeeze

In [37]:
x3 = torch.randn(1, 28, 1, 28)
result0 = x3.squeeze() # 크기가 1인 차원을 모두 제거.
result0.size()

torch.Size([28, 28])

In [38]:
result1 = x3.squeeze(2) # 크기가 1인 차원 중 2번 인덱스의 차원만 제거.
result1.size()

torch.Size([1, 28, 28])

#### (4) unsqueeze

In [39]:
x4 = torch.randn(28, 28)
# 크기가 1인 차원을 추가하고 싶은 차원의 인덱스 입력.
result2 = x4.unsqueeze(0)
result2.size()

torch.Size([1, 28, 28])

In [40]:
result2 = x4.unsqueeze(1)
result2.size()

torch.Size([28, 1, 28])

# 10. `View()`와 Contiguous
- `view()` 메소드로 나온 tensor는 원본 텐서와 메모리를 공유한다.
- 연속된 메모리를 갖는 tensor를 contiguous하다고 표현하며, contiguous한 tensor에서만 `view()` 메소드를 사용할 수 있다.
- 하지만 `reshape()` 메소드는 `view()` 메소드와 달리, tensor가 contiguous하지 않아도 정상적으로 코드가 실행된다.

In [41]:
v = torch.randn(3, 4)
result0 = v.view(2, 6)
result0.size()

torch.Size([2, 6])

In [42]:
result1 = v.view(-1, 2, 3) # -1 : 전체 원소 개수에 알아서 맞춰줌.
result1.size()

torch.Size([2, 2, 3])

In [43]:
v2 = torch.ones(2, 3)
v2_view = v2.view(-1)
v2_view

tensor([1., 1., 1., 1., 1., 1.])

In [44]:
v2[0, 0] = 0
v2_view

tensor([0., 1., 1., 1., 1., 1.])

# 11. tensor 합치기
#### (1) cat

In [45]:
x = torch.zeros(2, 3)
y = torch.ones(2, 3)

In [51]:
# concatenate
cat0 = torch.cat([x, y], dim=0) # 행 방향으로 합쳐짐.
cat1 = torch.cat([x, y], dim=1) # 열 방향으로 합쳐짐.

print(cat0)
print(cat0.size())
print('\n')
print(cat1)
print(cat1.size())

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([4, 3])


tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])
torch.Size([2, 6])


In [52]:
# cat이 안되는 경우
x = torch.zeros(2, 3)
y = torch.ones(2, 4)

cat0 = torch.cat((x,y), dim=0)

RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 3 but got size 4 for tensor number 1 in the list.

#### (2) stack
stack 메소드로 합칠 tensor들은 모두 형태가 같아야 함.

In [54]:
x = torch.zeros(2, 3)
y = torch.ones(2, 3)

stack과 cat 비교

In [55]:
stack_result = torch.stack([x, y], dim=0) # 0번 차원이 추가되면서
cat_result = torch.cat([x, y], dim=0)

print(stack_result.size())
print(stack_result, '\n')

print(cat_result.size())
print(cat_result)

torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) 

torch.Size([4, 3])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [56]:
stack_result_dim2 = torch.stack([x, y], dim=2) # 2번 차원이 추가되면서
print(stack_result_dim2.size())
print(stack_result_dim2)

torch.Size([2, 3, 2])
tensor([[[0., 1.],
         [0., 1.],
         [0., 1.]],

        [[0., 1.],
         [0., 1.],
         [0., 1.]]])


# 12. tensor 나누기
#### (1) split : 크기를 지정해서 나눔

In [57]:
x = torch.tensor(
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10],
    ]
)
x.size()

torch.Size([2, 5])

In [58]:
# 0번 차원을 기준으로 크기가 1이 되도록 나눔.
x.split(1, dim=0)

(tensor([[1, 2, 3, 4, 5]]), tensor([[ 6,  7,  8,  9, 10]]))

In [59]:
# 1번 차원을 기준으로 크기가 2가 되도록 나눔.
x.split(2, dim=1)

(tensor([[1, 2],
         [6, 7]]),
 tensor([[3, 4],
         [8, 9]]),
 tensor([[ 5],
         [10]]))

--> 5가 2로 나누어 떨어지지 않기 때문에 마지막 텐서는 2x1텐서가 됨.

#### (2) chunk : 개수를 지정해서 나눔

In [60]:
# 0번 차원을 기준으로 텐서 2개가 되도록 나눔.
x.chunk(2, dim=0)

(tensor([[1, 2, 3, 4, 5]]), tensor([[ 6,  7,  8,  9, 10]]))

In [61]:
# 1번 차원을 기준으로 텐서 3개가 되도록 나눔.
x.chunk(3, dim=1)

(tensor([[1, 2],
         [6, 7]]),
 tensor([[3, 4],
         [8, 9]]),
 tensor([[ 5],
         [10]]))

--> 5가 정확히 3등분 되지 않기 때문에 마지막 텐서가 2x1 텐서가 됨.

In [62]:
# 1번 차원을 기준으로 4개가 되도록 나눔.
x.chunk(4, dim=1)

(tensor([[1, 2],
         [6, 7]]),
 tensor([[3, 4],
         [8, 9]]),
 tensor([[ 5],
         [10]]))

--> 넷으로 나누려 했지만 셋으로 나뉘어짐.