<a href="https://colab.research.google.com/github/leejsya/PyTorch/blob/main/Tensor_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 기본 tensor 다루기


In [ ]:
import numpy as np
import torch

#### 1. list -> tensor

In [ ]:
data_list = [1, 2]
tensor = torch.tensor(data_list)

In [ ]:
print(f"tensor: {tensor}\n")
print(f"class type: {type(tensor)}\n")
print(f"data type: {tensor.dtype}\n")
print(f"dimension: {tensor.ndim}\n")
print(f"shape: {tensor.shape}") # tensor.size()와 같은 결과

tensor: tensor([1, 2])

class type: <class 'torch.Tensor'>

data type: torch.int64

dimension: 1

shape: torch.Size([2])


#### 2. np array -> tensor

In [ ]:
data_np = np.array(
    [[1, 2],
    [3, 4]]
)

In [ ]:
# 방법 1 : tensor()
tensor_np = torch.tensor(data_np)  # data_np의 데이터를 복사해서 tensor를 생성.(메모리 공유 x)
tensor_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
# 방법 2 : from_numpy()
tensor_from_numpy = torch.from_numpy(data_np) # data_np의 데이터를 가져와 tensor를 생성. (메모리 공유)
tensor_from_numpy

tensor([[1, 2],
        [3, 4]])

In [ ]:
# 차이점
data_np[0, 0] = -1
print(f"tensor():\n{tensor_np}\n")
print(f"from_numpy():\n{tensor_from_numpy}")

tensor():
tensor([[1, 2],
        [3, 4]])

from_numpy():
tensor([[-1,  2],
        [ 3,  4]])


두 결과가 다른 것을 볼 수 있다.

#### 3. 데이터 타입 지정


In [ ]:
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
tensor.dtype

torch.float32

#### 4. random값 tensor 생성
- 0과 1 사이의 랜덤한 값으로 tensor 생성.

In [ ]:
tensor1 = torch.rand(2, 3)
tensor2 = torch.rand([2, 3])
tensor3 = torch.rand((2, 3))
# 모두 같은 의미

In [ ]:
print(f"tensor1: {tensor1}\n")
print(f"tensor2: {tensor2}\n")
print(f"tensor3: {tensor3}\n")

tensor1: tensor([[0.0853, 0.9952, 0.4474],
        [0.3764, 0.1966, 0.7294]])

tensor2: tensor([[0.0524, 0.0139, 0.3095],
        [0.7537, 0.2381, 0.6855]])

tensor3: tensor([[0.7529, 0.2662, 0.5159],
        [0.4305, 0.0105, 0.2088]])



In [ ]:
# 만약 0과 10 사이의 랜덤한 값으로 tensor를 생성하려면
min_val = 0
max_val = 10
rand_tensor = min_val + (max_val - min_val) * torch.rand(2, 3)
rand_tensor

tensor([[5.3730, 1.1184, 4.7291],
        [0.6197, 7.5523, 6.9968]])

- avg가 0, std가 1인 random값 tensor 생성.

In [ ]:
# avg가 0, std가 1인 random tensor 생성.
tensor = torch.randn(2, 3)
tensor

tensor([[ 0.0049,  0.9788, -0.9582],
        [ 0.0601, -0.1068,  0.8382]])

In [ ]:
# 만약 avg가 5, std가 2인 random tensor를 생성하려면

In [ ]:
avg = 5
std = 2
tensor = avg + 2 * torch.randn(2, 3)
tensor

tensor([[7.2808, 2.0554, 4.9251],
        [7.8385, 5.7164, 6.4719]])

#### 5. 특정한 값 tensor 생성

In [ ]:
# 값이 전부 0인 tensor
zeros_tensor = torch.zeros(2, 3)
zeros_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# 값이 전부 1인 tensor
ones_tensor = torch.ones(2, 3)
ones_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# 값이 전부 7인 tensor
s_tensor = torch.full((2, 3), 7)
s_tensor

tensor([[7, 7, 7],
        [7, 7, 7]])

#### 6. tensor -> np array 변환

In [ ]:
t_tensor = torch.ones(2, 2)
t_tensor

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
# 첫 번째 방법 : numpy()
np_array = t_tensor.numpy() # t_tensor와 메모리를 공유.
np_array

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
# 두 번째 방법 : np.array(tensor)
np_array2 = np.array(t_tensor) # t_tensor와 메모리를 공유하지 않음.
np_array2

/tmp/ipykernel_1740/3246174616.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  np_array2 = np.array(t_tensor) # t_tensor와 메모리를 공유하지 않음.


array([[1., 1.],
       [1., 1.]], dtype=float32)

In [ ]:
t_tensor[0, 0] = -1

In [ ]:
# 차이점
print(f"numpy():\n{np_array}\n")
print(f"np.array():\n{np_array2}\n")

numpy():
[[-1.  1.]
 [ 1.  1.]]

np.array():
[[1. 1.]
 [1. 1.]]



# 기본 tensor 연산

In [ ]:
a = torch.tensor(
    [[1, 2],
     [3, 4]]
)
b = torch.tensor(
    [[1, 1],
     [2, 2]]
)

In [ ]:
print(a + b)
print(torch.add(a, b))

tensor([[2, 3],
        [5, 6]])
tensor([[2, 3],
        [5, 6]])


In [ ]:
print(a * b)
print(torch.multiply(a, b))

tensor([[1, 2],
        [6, 8]])
tensor([[1, 2],
        [6, 8]])


In [ ]:
# 행렬 곱은 두 행렬의 데이터 타입이 일치해야만 연산 가능.
print(torch.matmul(a, b))
print(a @ b)

tensor([[ 5,  5],
        [11, 11]])
tensor([[ 5,  5],
        [11, 11]])


In [ ]:
# 데이터 타입 변경
print(f"old: {a.dtype}")
a_new = a.to(torch.float32)
print(f"new: {a_new.dtype}")

old: torch.int64
new: torch.float32
